"""empty message

Revision ID: b32ce364029d
Revises: 
Create Date: 2021-09-09 19:43:52.637747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32ce364029d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Movie')
    op.drop_table('Actor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Actor',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Actor_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Actor_pkey')
    )
    op.create_table('Movie',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Movie_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('releaseDate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Movie_pkey')
    )
    # ### end Alembic commands ###
